# Generated by Django 3.1.2 on 2020-10-08 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='datetime the object was created', verbose_name='created_at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='datetime the object was modified', verbose_name='modified_at')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
    ]
