# Generated by Django 3.1.2 on 2020-10-10 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='datetime the object was created', verbose_name='created_at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='datetime the object was modified', verbose_name='modified_at')),
                ('region', models.CharField(max_length=100, verbose_name='Comarca')),
                ('city', models.CharField(max_length=100)),
                ('neighborhood', models.CharField(max_length=100, null=True)),
                ('size', models.CharField(choices=[('LESS_THAN_60', 'Menos de 60'), ('BETWEEN_60_AND_80', 'Entre 60 y 80'), ('BETWEEN_80_AND_100', 'Entre 80 y 100'), ('BETWEEN_100_AND_120', 'Entre 100 y 120'), ('MORE_THAN_120', 'Más de 120')], max_length=20)),
                ('house_price', models.IntegerField()),
                ('comment', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=250)),
                ('wants_contact', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'Contactos de formulario de autopromoción',
            },
        ),
    ]
