# Generated by Django 3.1.2 on 2020-10-27 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoproject', '0002_auto_20201018_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formcontact',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='datetime the object was created', verbose_name='Creat'),
        ),
        migrations.AlterField(
            model_name='formcontact',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='datetime the object was modified', verbose_name='Actualitzat'),
        ),
    ]
