# Generated by Django 3.1.2 on 2020-10-31 17:56

import autoproject.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoproject', '0003_auto_20201027_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='formcontact',
            name='rooms',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('>5', '>5')], default=2, max_length=30, verbose_name='Habitacions'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='formcontact',
            name='house_price',
            field=models.PositiveIntegerField(validators=[autoproject.validators.validate_house_price_value], verbose_name='Preu'),
        ),
        migrations.AlterField(
            model_name='formcontact',
            name='wants_contact',
            field=models.BooleanField(verbose_name='Contacte'),
        ),
    ]
