# Generated by Django 3.1.2 on 2020-11-10 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoproject', '0004_auto_20201031_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='formcontact',
            name='browser',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Navegador'),
        ),
        migrations.AddField(
            model_name='formcontact',
            name='browser_family',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Versió de navegador'),
        ),
        migrations.AddField(
            model_name='formcontact',
            name='device_brand',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Marca del dispositiu'),
        ),
        migrations.AddField(
            model_name='formcontact',
            name='device_family',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Familia de dispositiu'),
        ),
        migrations.AddField(
            model_name='formcontact',
            name='device_model',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Model del dispositiu'),
        ),
        migrations.AddField(
            model_name='formcontact',
            name='ip',
            field=models.GenericIPAddressField(null=True, verbose_name='IP'),
        ),
        migrations.AddField(
            model_name='formcontact',
            name='os',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Sistema Operatiu'),
        ),
        migrations.AddField(
            model_name='formcontact',
            name='os_version',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Versió de sistema operatiu'),
        ),
        migrations.AddField(
            model_name='formcontact',
            name='raw_user_agent',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='User Agent'),
        ),
        migrations.AlterField(
            model_name='formcontact',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text="Data en la l'objecte va ser creat.", verbose_name='Creat'),
        ),
        migrations.AlterField(
            model_name='formcontact',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text="Data en la l'objecte ha sigut actualitzat.", verbose_name='Actualitzat'),
        ),
    ]
