# Generated by Django 3.1.2 on 2020-11-10 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autoproject', '0005_auto_20201110_2013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formcontact',
            old_name='browser_family',
            new_name='browser_version',
        ),
    ]
