# Generated by Django 3.1.2 on 2021-01-17 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoproject', '0007_auto_20201110_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formcontact',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Telf'),
        ),
    ]
