# Generated by Django 3.1.2 on 2021-01-17 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoproject', '0008_auto_20210117_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formcontact',
            name='comment',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Comentari'),
        ),
    ]
