# Generated by Django 3.1.2 on 2020-10-18 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='datetime the object was created', verbose_name='created_at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='datetime the object was modified', verbose_name='modified_at')),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('maps_location', models.CharField(max_length=256)),
                ('properties_number_total', models.IntegerField()),
                ('properties_number_rest', models.IntegerField()),
                ('min_price', models.IntegerField()),
                ('status', models.CharField(choices=[('active', 'Activa'), ('finished', 'Finalitzada')], max_length=20)),
                ('home_page', models.BooleanField(verbose_name="Ha d'apareixer a la pàgina principal?")),
            ],
            options={
                'verbose_name': 'Projecte',
                'verbose_name_plural': 'Projectes',
            },
        ),
        migrations.CreateModel(
            name='ProjectContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='datetime the object was created', verbose_name='created_at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='datetime the object was modified', verbose_name='modified_at')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=100)),
                ('comment', models.TextField()),
            ],
            options={
                'verbose_name': 'Contacte de Projecte',
                'verbose_name_plural': 'Contactes de Projecte',
            },
        ),
    ]
