# Generated by Django 3.1.2 on 2020-10-27 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autopromotion', '0004_project_amenties'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='datetime the object was created', verbose_name='Creat'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(default='', verbose_name='Descripció'),
        ),
        migrations.AlterField(
            model_name='project',
            name='home_page',
            field=models.BooleanField(default=False, help_text="Ha d'aparèixer a la pàgina principal?", verbose_name='Pàgina principal?'),
        ),
        migrations.AlterField(
            model_name='project',
            name='location',
            field=models.CharField(max_length=100, verbose_name='Localització'),
        ),
        migrations.AlterField(
            model_name='project',
            name='maps_location',
            field=models.CharField(max_length=256, verbose_name='Localització Google Maps'),
        ),
        migrations.AlterField(
            model_name='project',
            name='min_price',
            field=models.IntegerField(default=100000, verbose_name='Preu mínim'),
        ),
        migrations.AlterField(
            model_name='project',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='datetime the object was modified', verbose_name='Actualitzat'),
        ),
        migrations.AlterField(
            model_name='project',
            name='properties_number_rest',
            field=models.IntegerField(default=0, help_text='Nombre de propietats restants que encara queden en el projecte', verbose_name='Propietats restants'),
        ),
        migrations.AlterField(
            model_name='project',
            name='properties_number_total',
            field=models.IntegerField(default=0, help_text='Nombre de propietats totals del projecte', verbose_name='Propietats totals'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('active', 'Activa'), ('finished', 'Finalitzat')], max_length=20, verbose_name='Estat'),
        ),
        migrations.AlterField(
            model_name='project',
            name='subtitle',
            field=models.CharField(max_length=200, verbose_name='Subtítol'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Títol'),
        ),
        migrations.AlterField(
            model_name='projectcontact',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='datetime the object was created', verbose_name='Creat'),
        ),
        migrations.AlterField(
            model_name='projectcontact',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='datetime the object was modified', verbose_name='Actualitzat'),
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='datetime the object was created', verbose_name='Creat')),
                ('modified', models.DateTimeField(auto_now=True, help_text='datetime the object was modified', verbose_name='Actualitzat')),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='project_images')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autopromotion.project')),
            ],
            options={
                'verbose_name': 'Imatge de Projecte',
                'verbose_name_plural': 'Imatges de Projecte',
            },
        ),
    ]
