# Generated by Django 3.1.2 on 2020-10-27 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autopromotion', '0005_auto_20201027_2158'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectimage',
            old_name='property',
            new_name='project',
        ),
    ]
