# Generated by Django 3.1.2 on 2020-10-28 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autopromotion', '0006_auto_20201027_2214'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectcontact',
            old_name='property',
            new_name='project',
        ),
        migrations.RemoveField(
            model_name='projectimage',
            name='name',
        ),
    ]
