# Generated by Django 3.1.2 on 2020-11-10 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autopromotion', '0007_auto_20201028_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text="Data en la l'objecte va ser creat.", verbose_name='Creat'),
        ),
        migrations.AlterField(
            model_name='project',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text="Data en la l'objecte ha sigut actualitzat.", verbose_name='Actualitzat'),
        ),
        migrations.AlterField(
            model_name='projectcontact',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text="Data en la l'objecte va ser creat.", verbose_name='Creat'),
        ),
        migrations.AlterField(
            model_name='projectcontact',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text="Data en la l'objecte ha sigut actualitzat.", verbose_name='Actualitzat'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text="Data en la l'objecte va ser creat.", verbose_name='Creat'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text="Data en la l'objecte ha sigut actualitzat.", verbose_name='Actualitzat'),
        ),
    ]
