# Generated by Django 3.1.2 on 2020-11-23 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autopromotion', '0008_auto_20201110_2005'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text="Data en la l'objecte va ser creat.", verbose_name='Creat')),
                ('modified', models.DateTimeField(auto_now=True, help_text="Data en la l'objecte ha sigut actualitzat.", verbose_name='Actualitzat')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=100)),
                ('comment', models.TextField()),
            ],
            options={
                'verbose_name': 'Contacte',
                'verbose_name_plural': 'Contactes',
            },
        ),
    ]
