# Generated by Django 3.1.2 on 2021-01-17 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autopromotion', '0009_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='grid_image',
            field=models.ImageField(default='', upload_to='project_images'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='file',
            field=models.ImageField(upload_to='project_images'),
        ),
    ]
